spring:
  data:
    hbase:
      quorum: 196.168.168.209,196.168.168.210,196.168.168.208
      clientPort: 2181
      period: 6000000
      maxSize: 100000000
  datasource:
    oracle:
      driver-class-name: oracle.jdbc.driver.OracleDriver
      jdbc-url: jdbc:oracle:thin:@193.100.100.225:1521:orcl
      username: CONVERGENCE
      password: CONVERGENCE
mybatis:
  mapper-locations: classpath:Mapper/peopleMapper.xml
  type-aliases-package: com.sirc.hbase.pojo
